
import { User, UserType, Vibes, Plan, Post, Biotype, Gender, SexualOrientation, TrustLevel, Moment, PresenceStatus } from './types';

export const MOCK_CURRENT_USER: User = {
  id: '000001',
  nickname: 'CASAL BEIJO',
  email: 'casalbeijo@libido.app',
  serialNumber: '000001',
  age: 32,
  city: 'RIO DE JANEIRO - RJ',
  plan: Plan.GOLD,
  balance: 500,
  boosts_active: 2,
  is_premium: true,
  trustLevel: TrustLevel.OURO,
  avatar: 'https://picsum.photos/seed/me/400/400',
  biotype: Biotype.ATLETICO,
  bio: 'Proprietário da Matriz Libido. Explorando conexões seguras.',
  gender: Gender.MASCULINO,
  sexualOrientation: SexualOrientation.HETERO,
  type: UserType.HOMEM,
  lookingFor: [UserType.MULHER, UserType.CASAIS],
  height: 182,
  vibes: [Vibes.LIBERAL, Vibes.SWING],
  location: 'Volta Redonda, RJ',
  xp: 1500,
  level: 3,
  isOnline: true,
  status: PresenceStatus.ONLINE,
  verifiedAccount: true,
  verificationScore: 100,
  isGhostMode: false,
  hasBlurredGallery: false,
  gallery: [
    { id: 'g1', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800', timestamp: '2026-01-01' },
    { id: 'g2', url: 'https://images.unsplash.com/photo-1514525253361-bee8718a74a2?w=800', timestamp: '2026-01-02' },
    { id: 'g3', url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800', timestamp: '2026-01-03', isBlurred: true },
    { id: 'g4', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800', timestamp: '2026-01-04', isBlurred: true }
  ],
  vouches: [],
  badges: ['Pioneiro', 'Staff'],
  bookmarks: [],
  blockedUsers: [],
  matches: [],
  following: [],
  seenBy: [],
  boundaries: ['Sem envolvimento emocional'],
  behaviors: ['Curioso', 'Aberto'],
  bodyMods: [],
  bodyHair: 'Aparado',
  bodyArt: [],
  bondageExp: 'Iniciante',
  bucketList: [],
  bestMoments: [],
  bestFeature: 'Olhar',
  beveragePref: 'Gin',
  bestTime: 'Noite',
  braveryLevel: 8,
  busyMode: false,
  bookingPolicy: 'A combinar',
  lat: -22.5231,
  lon: -44.1042,
  isSubscriber: false,
  dailyProfileViews: 0,
  birthDate: '1995-01-01',
  rsvps: [],
  consentMatrix: [
    { id: 'soft', label: 'Soft Swing', value: 'sim' as any },
    { id: 'total', label: 'Troca Total', value: 'talvez' as any },
    { id: 'menage', label: 'Ménage', value: 'sim' as any }
  ],
  vouchScore: 98,
  isStealthMode: false,
  prefersBlurredPhotos: false
};

export const MOCK_USERS: User[] = [
  {
    id: '65a8d3a4-24b1-47d6-aec4-6819710abae8',
    nickname: 'casalx',
    avatar: 'https://images.unsplash.com/photo-1516054191318-7cd886c99773?w=400',
    age: 32,
    city: 'RIO DE JANEIRO - RJ',
    location: 'Campo Grande',
    plan: Plan.PREMIUM,
    is_premium: true,
    trustLevel: TrustLevel.OURO,
    type: UserType.CASAIS,
    lookingFor: [UserType.MULHER, UserType.CASAIS],
    lat: -22.9031,
    lon: -43.5590,
    is_mock: true,
    vibes: [Vibes.BDSM, Vibes.SWING],
    gallery: []
  },
  {
    id: 'm1',
    nickname: 'Ana & Bruno',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    age: 26,
    city: 'VOLTA REDONDA - RJ',
    plan: Plan.FREE,
    is_premium: false,
    trustLevel: TrustLevel.OURO,
    type: UserType.CASAIS,
    lookingFor: [UserType.MULHER, UserType.CASAIS],
    lat: -22.5231,
    lon: -44.1042,
    is_mock: true,
    vibes: [Vibes.LIBERAL],
    gallery: []
  },
  {
    id: 'm2',
    nickname: 'Carla',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
    age: 24,
    city: 'VOLTA REDONDA - RJ',
    plan: Plan.PREMIUM,
    is_premium: true,
    trustLevel: TrustLevel.PRATA,
    type: UserType.MULHER,
    lookingFor: [UserType.HOMEM, UserType.CASAIS],
    lat: -22.5568,
    lon: -44.1129,
    is_mock: true,
    vibes: [Vibes.VOYEUR],
    gallery: []
  }
];

export const MOCK_MOMENTS: Moment[] = [];
export const MOCK_POSTS: Post[] = [];
